### PR TITLE
Update vendored Terraform to 0.10.1

### PR DESCRIPTION
**Pull request by alexsomesan**
This is required in order to bump Terraform version to v0.10.1 in the tectonic-installer.

/cc: @sym3tri

### CODE REVIEW

**Comment by alexsomesan** [comment]
Can't add reviewers so I'll cc @dghubble here.

@s-urbaniak tested these changes in the context of the tectonic-installer

**Comment by dghubble** [comment]
> This is required

Based on? Can you elaborate on the issue you're seeing.

I've been using Terraform `0.10.0-dev` and just tested Terraform v0.10.1 with the current `terraform-provider-matchbox` plugin and its working nicely. The concern is that bumping the vendored version effectively sets the min Terraform version so this would drop 0.9.4+ support. We should have a final release in that series before merging this.

**Comment by dghubble** [comment]
Lemme tag a v0.2.2 this afternoon, so v0.9.x users can get the improved client error messages and we'll be ready if indeed there is a need for this.

**Comment by alexsomesan** [comment]
If your testing with TF 0.10.x works as expected, then there's no urgent dependency with the installer.

As we're bumping the installer to 0.10.x we're removing the TF plugin wrapper from it as well since plugins bring their own CLI now. That means we won't be hitting the TF version conflict on vendoring. So no urgency to merge this for the installer if it works as is.

**Comment by dghubble** [comment]
I don't quite follow "plugins bring their own CLI now". I just download the plugin and pop it in `~/.terraformrc` as usual for a 3rd party plugin, as described in the README for general users. I believe Tectonic is basically doing the same, but bundling the binary and using a TFSPACE trick of some sort, but same idea. We can verify with tectonic-installer itself too

**Comment by dghubble** [comment]
v0.2.2 is released

**Comment by dghubble** [comment]
Hm, with Terraform v0.10.1 installed locally, trying to use a local build of the tectonic-installer produces:

```
7 error(s) occurred:

* provider.matchbox: failed to load plugin to verify its signature: open /home/dghubble/workspace/go/src/github.com/coreos/tectonic-installer/installer/bin/linux/installer-TFSPACE-matchbox: no such file or directory
* provider.template: new or changed plugin executable
* provider.local: new or changed plugin executable
* provider.tls: new or changed plugin executable
* provider.random: new or changed plugin executable
* provider.null: new or changed plugin executable
* provider.archive: new or changed plugin executable
```

Notably, `terraform` v0.10.1 and the `terraform-provider-matchbox` work perfectly fine in normal usage from the command line, following the install docs here. Can you elaborate on tectonic-installer's plan to package your plugin? cc @Quentin-M

**Comment by dghubble** [comment]
We could probably bump this to a v0.10 version at some point. Terraform is on v0.11 now so we could probably reasonably drop v0.9 support.

**Comment by alexsomesan** [comment]
Closing this as it's grown stale.

**Pull request closed without merging**
