### PR TITLE
Add "cloud_id" to resource_profile

### PR DESCRIPTION
**Pull request by bencord0**
protobuf definition:
https://github.com/coreos/matchbox/blob/ddbe17cd315b77707fe19df604ab0b100a856cbb/matchbox/storage/storagepb/storage.proto#L27

### CODE REVIEW

**Comment by dghubble** [comment]
Have you had a chance to look at [Container Linux configs](https://coreos.com/os/docs/latest/provisioning.html) (i.e. Ignition-based)?

Matchbox does not provide a gRPC API for managing Cloud-config's and and we're not planning to develop Cloud-Config features further.

**Comment by dghubble** [comment]
Thanks for the interest though

**Comment by bencord0** [comment]
Thanks for the clarification about cloud-config support.

I'm using matchbox with the terraform bindings to spin up a network of machines that use cloud-init, not ignition. I am not using Container Linux based hosts.

I've previously written mechanisms that can create cloud-init configurations exposed on a local network webserver with a static route to 169.254.169.254 on my router. I've been investigating using terraform/matchbox as a replacement for this.

**Comment by dghubble** [comment]
Matchbox's (now deprecated) cloud-config support is for [coreos/coreos-cloudinit](https://github.com/coreos/coreos-cloudinit) which is a Container Linux specific subset of the broader cloud-config format. Even if Matchbox's cloud-config support was added here, its probably not what you want for other distros. For that, Matchbox has a generic template system. https://github.com/coreos/matchbox/issues/562

**Pull request closed without merging**
